databases:
  - name: render_test_01_db
    plan: free
    databaseName: render_test_01_db
    user: render_test_01_user

services:
  - type: web
    plan: free
    name: render_test_01_api
    runtime: python
    buildCommand: "./build.sh"
    #startCommand: "python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker"
    startCommand: "python -m daphne -b 0.0.0.0 -p 8000 config.asgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: render_test_01_db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4